# Generated by Django 4.0.5 on 2022-06-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='images',
            field=models.ImageField(blank='true', upload_to='backend_images'),
        ),
    ]
