# Generated by Django 4.0.5 on 2022-07-01 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_main_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=100)),
                ('main_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_name', to='myapp.main')),
            ],
        ),
    ]
