# Generated by Django 4.0.5 on 2022-07-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Asadbek', max_length=255)),
                ('color', models.CharField(default='red', max_length=255)),
                ('age', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
