# Generated by Django 4.0.5 on 2022-07-14 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('qarz', models.IntegerField(default=0)),
                ('img', models.ImageField(blank='true', upload_to='backend_images')),
            ],
        ),
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tovar_nomi', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('main_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.main')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.IntegerField()),
                ('main_foreign_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tovar')),
            ],
        ),
    ]
